version: "3.7"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: anbetec-db
    environment:
      POSTGRES_PASSWORD: anbetec
      POSTGRES_USER: postgres
      POSTGRES_DB: anbetec
    volumes:
      - 'db:/var/lib/postgresql/data'
    ports:
      - "5432:5432"


volumes:
  db:
